version: '3.8'
services:
  nextjs-app:
    image: carlomos/nextjs-app:dev
    container_name: is373-nextjs-dev
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      NODE_ENV: development