version: '3.8'
services:
  nextjs-app:
    image: carlomos/nextjs-app:master
    container_name: is373-nextjs
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    labels:
      - com.centurylinklabs.watchtower.enable=true